"$schema" = 'https://starship.rs/config-schema.json'

format = """
[â–‘â–’â–“](blue)\
$username\
[î‚´](bg:gray fg:blue)\
$directory\
[î‚´](fg:gray bg:dark_gray)\
$git_branch\
$git_status\
$nodejs\
$rust\
$ruby\
[î‚´](fg:dark_gray bg:none)\
\n$character"""

palette = 'tokyonight_night'

[palettes.tokyonight_night]
background = '#1a1b26'
blue = '#7aa2f7'
dark_gray = '#212736'
gray = '#3b4261'
nodejs_green = '#68a063'
ruby_red = '#cc342d'
rust_orange = '#d34516'

[character]
success_symbol = "[â¯](blue)"
error_symbol = "[â¯](blue)"
vimcmd_symbol = "[â®](blue)"

[username]
style_user = "bg:blue fg:background"
style_root = "bold fg:ruby_red bg:blue"
format = '[ $user ]($style)'

[directory]
style = "fg:blue bg:gray"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:dark_gray"
format = '[[ $symbol $branch ](fg:yellow bg:dark_gray)]($style)'

[git_status]
style = "bg:dark_gray"
format = '[[($all_status$ahead_behind )](fg:yellow bg:dark_gray)]($style)'

[nodejs]
symbol = "ó°™"
style = "bg:dark_gray"
format = '[[ $symbol ($version) ](fg:nodejs_green bg:dark_gray)]($style)'

[rust]
# symbol = "î¨"
symbol = "ğŸ¦€"
style = "bg:dark_gray"
format = '[[ $symbol ($version) ](fg:rust_orange bg:dark_gray)]($style)'

[ruby]
symbol = "ï»"
style = "bg:dark_gray"
format = '[[ $symbol ($version) ](fg:ruby_red bg:dark_gray)]($style)'
